import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Image optimization
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },
  
  // Headers for security and performance
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on'
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload'
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN'
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block'
          },
        ],
      },
    ];
  },

  // SEO Redirects
  async redirects() {
    return [
      // Contact page → Homepage with contact section
      {
        source: '/contact',
        destination: '/#contact',
        permanent: true,
      },
    ];
  },

  // Ensure dynamic city+service pages on Vercel serverless can read YAML
  // content files generated by the SEO content pipeline. (Next.js 16 moved
  // this from `experimental` to top-level.)
  outputFileTracingIncludes: {
    '/services/[service]/[city]': ['./content/cities/**/*.yaml'],
    '/services/[service]/[city]/page': ['./content/cities/**/*.yaml'],
  },

  // Experimental features
  experimental: {
    optimizePackageImports: ['lucide-react'],
  },
};

export default nextConfig;
