import Link from 'next/link';
import type { PageContent } from '@/lib/content/loadPageContent';
import { PHONE_DISPLAY, PHONE_NUMBER, BUSINESS_NAME } from '@/lib/utils';

interface SEOPageContentProps {
  content: PageContent;
  cityName?: string;
  serviceName?: string;
}

/**
 * Renders unique SEO content (intro, local context, common problems, FAQ)
 * sourced from a YAML file generated by the SEO content pipeline.
 *
 * Server Component — reads at build/SSR time.
 */
export default function SEOPageContent({
  content,
  cityName,
  serviceName,
}: SEOPageContentProps) {
  const lastUpdated = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  return (
    <section className="py-12 bg-white">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto space-y-10">
          {/* AEO: direct-answer lead (spoiler) + freshness signal */}
          <div className={content.answer ? 'border-l-4 border-blue-600 bg-blue-50 rounded-r-lg p-4' : ''}>
            {content.answer && (
              <p className="text-base md:text-lg font-medium text-gray-900 leading-relaxed">{content.answer}</p>
            )}
            <p className={`text-xs text-gray-500 ${content.answer ? 'mt-2' : ''}`}>Last updated {lastUpdated}</p>
          </div>

          {content.title && (
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900">
              {content.title}
            </h2>
          )}

          {content.intro && (
            <div className="text-gray-700">
              <p className="text-base md:text-lg leading-relaxed whitespace-pre-line">
                {content.intro}
              </p>
            </div>
          )}

          {content.localContext && (
            <div className="text-gray-700">
              <p className="text-base md:text-lg leading-relaxed whitespace-pre-line">
                {content.localContext}
              </p>
            </div>
          )}

          {content.commonProblems && content.commonProblems.length > 0 && (
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
                Common {serviceName || 'Project'} Concerns
                {cityName ? ` in ${cityName}` : ''}
              </h2>
              <div className="space-y-4">
                {content.commonProblems.map((problem, i) => (
                  <div
                    key={i}
                    className="bg-gray-50 rounded-lg p-5 border border-gray-200"
                  >
                    <h3 className="font-semibold text-gray-900 mb-2 text-lg">
                      {problem.title}
                    </h3>
                    <p className="text-gray-700 text-base leading-relaxed whitespace-pre-line">
                      {problem.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {content.whyChooseUs && (
            <div className="text-gray-700">
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-4">
                Why Choose {BUSINESS_NAME}
              </h2>
              <p className="text-base md:text-lg leading-relaxed whitespace-pre-line">
                {content.whyChooseUs}
              </p>
            </div>
          )}

          {content.faq && content.faq.length > 0 && (
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
                Frequently Asked Questions
              </h2>
              <div className="space-y-3">
                {content.faq.map((item, i) => (
                  <details
                    key={i}
                    className="bg-gray-50 rounded-lg p-5 group border border-gray-200"
                  >
                    <summary className="font-semibold text-gray-900 cursor-pointer list-none flex justify-between items-center text-lg">
                      <span>{item.q}</span>
                      <span className="ml-3 text-gold-500 group-open:rotate-180 transition-transform">
                        &#9660;
                      </span>
                    </summary>
                    <p className="text-gray-700 mt-3 text-base leading-relaxed whitespace-pre-line">
                      {item.a}
                    </p>
                  </details>
                ))}
              </div>
            </div>
          )}

          <div
            className="text-center rounded-lg p-6 border border-gray-200"
            style={{ backgroundColor: 'rgba(244, 185, 66, 0.08)' }}
          >
            <p className="text-lg font-semibold text-gray-900 mb-2">
              Ready to start your {serviceName || 'project'}
              {cityName ? ` in ${cityName}` : ''}?
            </p>
            <p className="text-gray-700 mb-4">
              Free on-site consultation with Vladislav. Line-item pricing — no
              vague ranges.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <a
                href={`tel:${PHONE_NUMBER}`}
                className="inline-block text-center px-6 py-3 rounded-lg font-semibold text-base transition shadow-md hover:shadow-lg"
                style={{ backgroundColor: '#F4B942', color: '#ffffff' }}
              >
                Call {PHONE_DISPLAY}
              </a>
              <Link
                href="/#request-service"
                className="inline-block text-center bg-gray-800 hover:bg-gray-900 text-white px-6 py-3 rounded-lg font-semibold text-base transition shadow-md hover:shadow-lg"
              >
                Request Free Quote
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
