import { cities } from '@/lib/data/cities';
import { indexableServiceCityPaths } from '@/lib/data/indexAllowlist';

/**
 * PHASE 2 SITEMAP
 * Remaining city pages + the service x city pages on the index allowlist.
 *
 * Service x city pages used to be listed by position (top 20 cities x first 6
 * services here, everything else in a phase 3 file). Now only pages that earn
 * attention are listed, wherever they sit in the grid; the list comes from
 * lib/data/indexAllowlist.ts, generated by
 * Clients/TopVolk/SEO/build-index-allowlist.py. Pages outside it render
 * noindex and must never appear in a sitemap.
 */
export async function GET() {
  const baseUrl = 'https://www.topvolk.org';
  const now = new Date().toISOString();

  // Remaining cities (the top 20 are in phase 1)
  const remainingCities = cities.slice(20);

  const urls: Array<{ loc: string; lastmod: string; changefreq: string; priority: number }> = [
    // Remaining city pages (cities 21+)
    ...remainingCities.map((city) => ({
      loc: `${baseUrl}/cities/${city.slug}`,
      lastmod: now,
      changefreq: 'weekly',
      priority: 0.75,
    })),

    // Service x city pages on the index allowlist
    ...indexableServiceCityPaths.map((path) => ({
      loc: `${baseUrl}${path}`,
      lastmod: now,
      changefreq: 'monthly',
      priority: 0.8,
    })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}
